// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Protocol_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Protocol_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Protocol_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Protocol_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Protocol_2eproto;
namespace Protocol {
class C_LOGIN;
struct C_LOGINDefaultTypeInternal;
extern C_LOGINDefaultTypeInternal _C_LOGIN_default_instance_;
class C_SIGNUP;
struct C_SIGNUPDefaultTypeInternal;
extern C_SIGNUPDefaultTypeInternal _C_SIGNUP_default_instance_;
class C_VERIFY_EMAIL_CODE;
struct C_VERIFY_EMAIL_CODEDefaultTypeInternal;
extern C_VERIFY_EMAIL_CODEDefaultTypeInternal _C_VERIFY_EMAIL_CODE_default_instance_;
class C_VERIFY_MAIL_REQ;
struct C_VERIFY_MAIL_REQDefaultTypeInternal;
extern C_VERIFY_MAIL_REQDefaultTypeInternal _C_VERIFY_MAIL_REQ_default_instance_;
class S_LOGIN;
struct S_LOGINDefaultTypeInternal;
extern S_LOGINDefaultTypeInternal _S_LOGIN_default_instance_;
class S_SIGNUP;
struct S_SIGNUPDefaultTypeInternal;
extern S_SIGNUPDefaultTypeInternal _S_SIGNUP_default_instance_;
class S_VERIFY_EMAIL_CODE;
struct S_VERIFY_EMAIL_CODEDefaultTypeInternal;
extern S_VERIFY_EMAIL_CODEDefaultTypeInternal _S_VERIFY_EMAIL_CODE_default_instance_;
class S_VERIFY_MAIL_REQ;
struct S_VERIFY_MAIL_REQDefaultTypeInternal;
extern S_VERIFY_MAIL_REQDefaultTypeInternal _S_VERIFY_MAIL_REQ_default_instance_;
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::Protocol::C_LOGIN* Arena::CreateMaybeMessage<::Protocol::C_LOGIN>(Arena*);
template<> ::Protocol::C_SIGNUP* Arena::CreateMaybeMessage<::Protocol::C_SIGNUP>(Arena*);
template<> ::Protocol::C_VERIFY_EMAIL_CODE* Arena::CreateMaybeMessage<::Protocol::C_VERIFY_EMAIL_CODE>(Arena*);
template<> ::Protocol::C_VERIFY_MAIL_REQ* Arena::CreateMaybeMessage<::Protocol::C_VERIFY_MAIL_REQ>(Arena*);
template<> ::Protocol::S_LOGIN* Arena::CreateMaybeMessage<::Protocol::S_LOGIN>(Arena*);
template<> ::Protocol::S_SIGNUP* Arena::CreateMaybeMessage<::Protocol::S_SIGNUP>(Arena*);
template<> ::Protocol::S_VERIFY_EMAIL_CODE* Arena::CreateMaybeMessage<::Protocol::S_VERIFY_EMAIL_CODE>(Arena*);
template<> ::Protocol::S_VERIFY_MAIL_REQ* Arena::CreateMaybeMessage<::Protocol::S_VERIFY_MAIL_REQ>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

// ===================================================================

class C_SIGNUP final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.C_SIGNUP) */ {
 public:
  inline C_SIGNUP() : C_SIGNUP(nullptr) {}
  ~C_SIGNUP() override;
  explicit PROTOBUF_CONSTEXPR C_SIGNUP(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C_SIGNUP(const C_SIGNUP& from);
  C_SIGNUP(C_SIGNUP&& from) noexcept
    : C_SIGNUP() {
    *this = ::std::move(from);
  }

  inline C_SIGNUP& operator=(const C_SIGNUP& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_SIGNUP& operator=(C_SIGNUP&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_SIGNUP& default_instance() {
    return *internal_default_instance();
  }
  static inline const C_SIGNUP* internal_default_instance() {
    return reinterpret_cast<const C_SIGNUP*>(
               &_C_SIGNUP_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(C_SIGNUP& a, C_SIGNUP& b) {
    a.Swap(&b);
  }
  inline void Swap(C_SIGNUP* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_SIGNUP* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C_SIGNUP* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<C_SIGNUP>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const C_SIGNUP& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const C_SIGNUP& from) {
    C_SIGNUP::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(C_SIGNUP* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.C_SIGNUP";
  }
  protected:
  explicit C_SIGNUP(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNicknameFieldNumber = 1,
    kPasswordFieldNumber = 2,
    kEmailFieldNumber = 3,
    kSkipEmailFieldNumber = 4,
  };
  // string nickname = 1;
  void clear_nickname();
  const std::string& nickname() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_nickname(ArgT0&& arg0, ArgT... args);
  std::string* mutable_nickname();
  PROTOBUF_NODISCARD std::string* release_nickname();
  void set_allocated_nickname(std::string* nickname);
  private:
  const std::string& _internal_nickname() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_nickname(const std::string& value);
  std::string* _internal_mutable_nickname();
  public:

  // string password = 2;
  void clear_password();
  const std::string& password() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_password(ArgT0&& arg0, ArgT... args);
  std::string* mutable_password();
  PROTOBUF_NODISCARD std::string* release_password();
  void set_allocated_password(std::string* password);
  private:
  const std::string& _internal_password() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_password(const std::string& value);
  std::string* _internal_mutable_password();
  public:

  // string email = 3;
  void clear_email();
  const std::string& email() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_email(ArgT0&& arg0, ArgT... args);
  std::string* mutable_email();
  PROTOBUF_NODISCARD std::string* release_email();
  void set_allocated_email(std::string* email);
  private:
  const std::string& _internal_email() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_email(const std::string& value);
  std::string* _internal_mutable_email();
  public:

  // bool skip_email = 4;
  void clear_skip_email();
  bool skip_email() const;
  void set_skip_email(bool value);
  private:
  bool _internal_skip_email() const;
  void _internal_set_skip_email(bool value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.C_SIGNUP)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr nickname_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr password_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr email_;
    bool skip_email_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class S_SIGNUP final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S_SIGNUP) */ {
 public:
  inline S_SIGNUP() : S_SIGNUP(nullptr) {}
  ~S_SIGNUP() override;
  explicit PROTOBUF_CONSTEXPR S_SIGNUP(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S_SIGNUP(const S_SIGNUP& from);
  S_SIGNUP(S_SIGNUP&& from) noexcept
    : S_SIGNUP() {
    *this = ::std::move(from);
  }

  inline S_SIGNUP& operator=(const S_SIGNUP& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_SIGNUP& operator=(S_SIGNUP&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_SIGNUP& default_instance() {
    return *internal_default_instance();
  }
  static inline const S_SIGNUP* internal_default_instance() {
    return reinterpret_cast<const S_SIGNUP*>(
               &_S_SIGNUP_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(S_SIGNUP& a, S_SIGNUP& b) {
    a.Swap(&b);
  }
  inline void Swap(S_SIGNUP* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_SIGNUP* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S_SIGNUP* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S_SIGNUP>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S_SIGNUP& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S_SIGNUP& from) {
    S_SIGNUP::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S_SIGNUP* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S_SIGNUP";
  }
  protected:
  explicit S_SIGNUP(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTempIdFieldNumber = 3,
    kSuccessFieldNumber = 1,
    kSkipEmailFieldNumber = 2,
  };
  // string temp_id = 3;
  void clear_temp_id();
  const std::string& temp_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_temp_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_temp_id();
  PROTOBUF_NODISCARD std::string* release_temp_id();
  void set_allocated_temp_id(std::string* temp_id);
  private:
  const std::string& _internal_temp_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_temp_id(const std::string& value);
  std::string* _internal_mutable_temp_id();
  public:

  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // bool skip_email = 2;
  void clear_skip_email();
  bool skip_email() const;
  void set_skip_email(bool value);
  private:
  bool _internal_skip_email() const;
  void _internal_set_skip_email(bool value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.S_SIGNUP)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr temp_id_;
    bool success_;
    bool skip_email_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class C_VERIFY_MAIL_REQ final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.C_VERIFY_MAIL_REQ) */ {
 public:
  inline C_VERIFY_MAIL_REQ() : C_VERIFY_MAIL_REQ(nullptr) {}
  ~C_VERIFY_MAIL_REQ() override;
  explicit PROTOBUF_CONSTEXPR C_VERIFY_MAIL_REQ(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C_VERIFY_MAIL_REQ(const C_VERIFY_MAIL_REQ& from);
  C_VERIFY_MAIL_REQ(C_VERIFY_MAIL_REQ&& from) noexcept
    : C_VERIFY_MAIL_REQ() {
    *this = ::std::move(from);
  }

  inline C_VERIFY_MAIL_REQ& operator=(const C_VERIFY_MAIL_REQ& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_VERIFY_MAIL_REQ& operator=(C_VERIFY_MAIL_REQ&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_VERIFY_MAIL_REQ& default_instance() {
    return *internal_default_instance();
  }
  static inline const C_VERIFY_MAIL_REQ* internal_default_instance() {
    return reinterpret_cast<const C_VERIFY_MAIL_REQ*>(
               &_C_VERIFY_MAIL_REQ_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(C_VERIFY_MAIL_REQ& a, C_VERIFY_MAIL_REQ& b) {
    a.Swap(&b);
  }
  inline void Swap(C_VERIFY_MAIL_REQ* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_VERIFY_MAIL_REQ* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C_VERIFY_MAIL_REQ* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<C_VERIFY_MAIL_REQ>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const C_VERIFY_MAIL_REQ& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const C_VERIFY_MAIL_REQ& from) {
    C_VERIFY_MAIL_REQ::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(C_VERIFY_MAIL_REQ* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.C_VERIFY_MAIL_REQ";
  }
  protected:
  explicit C_VERIFY_MAIL_REQ(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTempIdFieldNumber = 1,
  };
  // string temp_id = 1;
  void clear_temp_id();
  const std::string& temp_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_temp_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_temp_id();
  PROTOBUF_NODISCARD std::string* release_temp_id();
  void set_allocated_temp_id(std::string* temp_id);
  private:
  const std::string& _internal_temp_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_temp_id(const std::string& value);
  std::string* _internal_mutable_temp_id();
  public:

  // @@protoc_insertion_point(class_scope:Protocol.C_VERIFY_MAIL_REQ)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr temp_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class S_VERIFY_MAIL_REQ final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S_VERIFY_MAIL_REQ) */ {
 public:
  inline S_VERIFY_MAIL_REQ() : S_VERIFY_MAIL_REQ(nullptr) {}
  ~S_VERIFY_MAIL_REQ() override;
  explicit PROTOBUF_CONSTEXPR S_VERIFY_MAIL_REQ(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S_VERIFY_MAIL_REQ(const S_VERIFY_MAIL_REQ& from);
  S_VERIFY_MAIL_REQ(S_VERIFY_MAIL_REQ&& from) noexcept
    : S_VERIFY_MAIL_REQ() {
    *this = ::std::move(from);
  }

  inline S_VERIFY_MAIL_REQ& operator=(const S_VERIFY_MAIL_REQ& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_VERIFY_MAIL_REQ& operator=(S_VERIFY_MAIL_REQ&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_VERIFY_MAIL_REQ& default_instance() {
    return *internal_default_instance();
  }
  static inline const S_VERIFY_MAIL_REQ* internal_default_instance() {
    return reinterpret_cast<const S_VERIFY_MAIL_REQ*>(
               &_S_VERIFY_MAIL_REQ_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(S_VERIFY_MAIL_REQ& a, S_VERIFY_MAIL_REQ& b) {
    a.Swap(&b);
  }
  inline void Swap(S_VERIFY_MAIL_REQ* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_VERIFY_MAIL_REQ* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S_VERIFY_MAIL_REQ* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S_VERIFY_MAIL_REQ>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S_VERIFY_MAIL_REQ& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S_VERIFY_MAIL_REQ& from) {
    S_VERIFY_MAIL_REQ::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S_VERIFY_MAIL_REQ* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S_VERIFY_MAIL_REQ";
  }
  protected:
  explicit S_VERIFY_MAIL_REQ(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSuccessFieldNumber = 1,
  };
  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.S_VERIFY_MAIL_REQ)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    bool success_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class C_VERIFY_EMAIL_CODE final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.C_VERIFY_EMAIL_CODE) */ {
 public:
  inline C_VERIFY_EMAIL_CODE() : C_VERIFY_EMAIL_CODE(nullptr) {}
  ~C_VERIFY_EMAIL_CODE() override;
  explicit PROTOBUF_CONSTEXPR C_VERIFY_EMAIL_CODE(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C_VERIFY_EMAIL_CODE(const C_VERIFY_EMAIL_CODE& from);
  C_VERIFY_EMAIL_CODE(C_VERIFY_EMAIL_CODE&& from) noexcept
    : C_VERIFY_EMAIL_CODE() {
    *this = ::std::move(from);
  }

  inline C_VERIFY_EMAIL_CODE& operator=(const C_VERIFY_EMAIL_CODE& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_VERIFY_EMAIL_CODE& operator=(C_VERIFY_EMAIL_CODE&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_VERIFY_EMAIL_CODE& default_instance() {
    return *internal_default_instance();
  }
  static inline const C_VERIFY_EMAIL_CODE* internal_default_instance() {
    return reinterpret_cast<const C_VERIFY_EMAIL_CODE*>(
               &_C_VERIFY_EMAIL_CODE_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(C_VERIFY_EMAIL_CODE& a, C_VERIFY_EMAIL_CODE& b) {
    a.Swap(&b);
  }
  inline void Swap(C_VERIFY_EMAIL_CODE* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_VERIFY_EMAIL_CODE* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C_VERIFY_EMAIL_CODE* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<C_VERIFY_EMAIL_CODE>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const C_VERIFY_EMAIL_CODE& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const C_VERIFY_EMAIL_CODE& from) {
    C_VERIFY_EMAIL_CODE::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(C_VERIFY_EMAIL_CODE* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.C_VERIFY_EMAIL_CODE";
  }
  protected:
  explicit C_VERIFY_EMAIL_CODE(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTempIdFieldNumber = 1,
    kVerifyCodeFieldNumber = 2,
  };
  // string temp_id = 1;
  void clear_temp_id();
  const std::string& temp_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_temp_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_temp_id();
  PROTOBUF_NODISCARD std::string* release_temp_id();
  void set_allocated_temp_id(std::string* temp_id);
  private:
  const std::string& _internal_temp_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_temp_id(const std::string& value);
  std::string* _internal_mutable_temp_id();
  public:

  // string verify_code = 2;
  void clear_verify_code();
  const std::string& verify_code() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_verify_code(ArgT0&& arg0, ArgT... args);
  std::string* mutable_verify_code();
  PROTOBUF_NODISCARD std::string* release_verify_code();
  void set_allocated_verify_code(std::string* verify_code);
  private:
  const std::string& _internal_verify_code() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_verify_code(const std::string& value);
  std::string* _internal_mutable_verify_code();
  public:

  // @@protoc_insertion_point(class_scope:Protocol.C_VERIFY_EMAIL_CODE)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr temp_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr verify_code_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class S_VERIFY_EMAIL_CODE final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S_VERIFY_EMAIL_CODE) */ {
 public:
  inline S_VERIFY_EMAIL_CODE() : S_VERIFY_EMAIL_CODE(nullptr) {}
  ~S_VERIFY_EMAIL_CODE() override;
  explicit PROTOBUF_CONSTEXPR S_VERIFY_EMAIL_CODE(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S_VERIFY_EMAIL_CODE(const S_VERIFY_EMAIL_CODE& from);
  S_VERIFY_EMAIL_CODE(S_VERIFY_EMAIL_CODE&& from) noexcept
    : S_VERIFY_EMAIL_CODE() {
    *this = ::std::move(from);
  }

  inline S_VERIFY_EMAIL_CODE& operator=(const S_VERIFY_EMAIL_CODE& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_VERIFY_EMAIL_CODE& operator=(S_VERIFY_EMAIL_CODE&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_VERIFY_EMAIL_CODE& default_instance() {
    return *internal_default_instance();
  }
  static inline const S_VERIFY_EMAIL_CODE* internal_default_instance() {
    return reinterpret_cast<const S_VERIFY_EMAIL_CODE*>(
               &_S_VERIFY_EMAIL_CODE_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(S_VERIFY_EMAIL_CODE& a, S_VERIFY_EMAIL_CODE& b) {
    a.Swap(&b);
  }
  inline void Swap(S_VERIFY_EMAIL_CODE* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_VERIFY_EMAIL_CODE* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S_VERIFY_EMAIL_CODE* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S_VERIFY_EMAIL_CODE>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S_VERIFY_EMAIL_CODE& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S_VERIFY_EMAIL_CODE& from) {
    S_VERIFY_EMAIL_CODE::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S_VERIFY_EMAIL_CODE* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S_VERIFY_EMAIL_CODE";
  }
  protected:
  explicit S_VERIFY_EMAIL_CODE(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSuccessFieldNumber = 1,
    kExpiredFieldNumber = 2,
  };
  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // bool expired = 2;
  void clear_expired();
  bool expired() const;
  void set_expired(bool value);
  private:
  bool _internal_expired() const;
  void _internal_set_expired(bool value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.S_VERIFY_EMAIL_CODE)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    bool success_;
    bool expired_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class C_LOGIN final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.C_LOGIN) */ {
 public:
  inline C_LOGIN() : C_LOGIN(nullptr) {}
  ~C_LOGIN() override;
  explicit PROTOBUF_CONSTEXPR C_LOGIN(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C_LOGIN(const C_LOGIN& from);
  C_LOGIN(C_LOGIN&& from) noexcept
    : C_LOGIN() {
    *this = ::std::move(from);
  }

  inline C_LOGIN& operator=(const C_LOGIN& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_LOGIN& operator=(C_LOGIN&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_LOGIN& default_instance() {
    return *internal_default_instance();
  }
  static inline const C_LOGIN* internal_default_instance() {
    return reinterpret_cast<const C_LOGIN*>(
               &_C_LOGIN_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(C_LOGIN& a, C_LOGIN& b) {
    a.Swap(&b);
  }
  inline void Swap(C_LOGIN* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_LOGIN* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C_LOGIN* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<C_LOGIN>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const C_LOGIN& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const C_LOGIN& from) {
    C_LOGIN::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(C_LOGIN* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.C_LOGIN";
  }
  protected:
  explicit C_LOGIN(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNicknameFieldNumber = 1,
    kPasswordFieldNumber = 2,
  };
  // string nickname = 1;
  void clear_nickname();
  const std::string& nickname() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_nickname(ArgT0&& arg0, ArgT... args);
  std::string* mutable_nickname();
  PROTOBUF_NODISCARD std::string* release_nickname();
  void set_allocated_nickname(std::string* nickname);
  private:
  const std::string& _internal_nickname() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_nickname(const std::string& value);
  std::string* _internal_mutable_nickname();
  public:

  // string password = 2;
  void clear_password();
  const std::string& password() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_password(ArgT0&& arg0, ArgT... args);
  std::string* mutable_password();
  PROTOBUF_NODISCARD std::string* release_password();
  void set_allocated_password(std::string* password);
  private:
  const std::string& _internal_password() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_password(const std::string& value);
  std::string* _internal_mutable_password();
  public:

  // @@protoc_insertion_point(class_scope:Protocol.C_LOGIN)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr nickname_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr password_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class S_LOGIN final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S_LOGIN) */ {
 public:
  inline S_LOGIN() : S_LOGIN(nullptr) {}
  ~S_LOGIN() override;
  explicit PROTOBUF_CONSTEXPR S_LOGIN(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S_LOGIN(const S_LOGIN& from);
  S_LOGIN(S_LOGIN&& from) noexcept
    : S_LOGIN() {
    *this = ::std::move(from);
  }

  inline S_LOGIN& operator=(const S_LOGIN& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_LOGIN& operator=(S_LOGIN&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_LOGIN& default_instance() {
    return *internal_default_instance();
  }
  static inline const S_LOGIN* internal_default_instance() {
    return reinterpret_cast<const S_LOGIN*>(
               &_S_LOGIN_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(S_LOGIN& a, S_LOGIN& b) {
    a.Swap(&b);
  }
  inline void Swap(S_LOGIN* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_LOGIN* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S_LOGIN* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S_LOGIN>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S_LOGIN& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S_LOGIN& from) {
    S_LOGIN::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S_LOGIN* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S_LOGIN";
  }
  protected:
  explicit S_LOGIN(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSuccessFieldNumber = 1,
  };
  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.S_LOGIN)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    bool success_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// C_SIGNUP

// string nickname = 1;
inline void C_SIGNUP::clear_nickname() {
  _impl_.nickname_.ClearToEmpty();
}
inline const std::string& C_SIGNUP::nickname() const {
  // @@protoc_insertion_point(field_get:Protocol.C_SIGNUP.nickname)
  return _internal_nickname();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void C_SIGNUP::set_nickname(ArgT0&& arg0, ArgT... args) {
 
 _impl_.nickname_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.C_SIGNUP.nickname)
}
inline std::string* C_SIGNUP::mutable_nickname() {
  std::string* _s = _internal_mutable_nickname();
  // @@protoc_insertion_point(field_mutable:Protocol.C_SIGNUP.nickname)
  return _s;
}
inline const std::string& C_SIGNUP::_internal_nickname() const {
  return _impl_.nickname_.Get();
}
inline void C_SIGNUP::_internal_set_nickname(const std::string& value) {
  
  _impl_.nickname_.Set(value, GetArenaForAllocation());
}
inline std::string* C_SIGNUP::_internal_mutable_nickname() {
  
  return _impl_.nickname_.Mutable(GetArenaForAllocation());
}
inline std::string* C_SIGNUP::release_nickname() {
  // @@protoc_insertion_point(field_release:Protocol.C_SIGNUP.nickname)
  return _impl_.nickname_.Release();
}
inline void C_SIGNUP::set_allocated_nickname(std::string* nickname) {
  if (nickname != nullptr) {
    
  } else {
    
  }
  _impl_.nickname_.SetAllocated(nickname, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.nickname_.IsDefault()) {
    _impl_.nickname_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.C_SIGNUP.nickname)
}

// string password = 2;
inline void C_SIGNUP::clear_password() {
  _impl_.password_.ClearToEmpty();
}
inline const std::string& C_SIGNUP::password() const {
  // @@protoc_insertion_point(field_get:Protocol.C_SIGNUP.password)
  return _internal_password();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void C_SIGNUP::set_password(ArgT0&& arg0, ArgT... args) {
 
 _impl_.password_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.C_SIGNUP.password)
}
inline std::string* C_SIGNUP::mutable_password() {
  std::string* _s = _internal_mutable_password();
  // @@protoc_insertion_point(field_mutable:Protocol.C_SIGNUP.password)
  return _s;
}
inline const std::string& C_SIGNUP::_internal_password() const {
  return _impl_.password_.Get();
}
inline void C_SIGNUP::_internal_set_password(const std::string& value) {
  
  _impl_.password_.Set(value, GetArenaForAllocation());
}
inline std::string* C_SIGNUP::_internal_mutable_password() {
  
  return _impl_.password_.Mutable(GetArenaForAllocation());
}
inline std::string* C_SIGNUP::release_password() {
  // @@protoc_insertion_point(field_release:Protocol.C_SIGNUP.password)
  return _impl_.password_.Release();
}
inline void C_SIGNUP::set_allocated_password(std::string* password) {
  if (password != nullptr) {
    
  } else {
    
  }
  _impl_.password_.SetAllocated(password, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.password_.IsDefault()) {
    _impl_.password_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.C_SIGNUP.password)
}

// string email = 3;
inline void C_SIGNUP::clear_email() {
  _impl_.email_.ClearToEmpty();
}
inline const std::string& C_SIGNUP::email() const {
  // @@protoc_insertion_point(field_get:Protocol.C_SIGNUP.email)
  return _internal_email();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void C_SIGNUP::set_email(ArgT0&& arg0, ArgT... args) {
 
 _impl_.email_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.C_SIGNUP.email)
}
inline std::string* C_SIGNUP::mutable_email() {
  std::string* _s = _internal_mutable_email();
  // @@protoc_insertion_point(field_mutable:Protocol.C_SIGNUP.email)
  return _s;
}
inline const std::string& C_SIGNUP::_internal_email() const {
  return _impl_.email_.Get();
}
inline void C_SIGNUP::_internal_set_email(const std::string& value) {
  
  _impl_.email_.Set(value, GetArenaForAllocation());
}
inline std::string* C_SIGNUP::_internal_mutable_email() {
  
  return _impl_.email_.Mutable(GetArenaForAllocation());
}
inline std::string* C_SIGNUP::release_email() {
  // @@protoc_insertion_point(field_release:Protocol.C_SIGNUP.email)
  return _impl_.email_.Release();
}
inline void C_SIGNUP::set_allocated_email(std::string* email) {
  if (email != nullptr) {
    
  } else {
    
  }
  _impl_.email_.SetAllocated(email, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.email_.IsDefault()) {
    _impl_.email_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.C_SIGNUP.email)
}

// bool skip_email = 4;
inline void C_SIGNUP::clear_skip_email() {
  _impl_.skip_email_ = false;
}
inline bool C_SIGNUP::_internal_skip_email() const {
  return _impl_.skip_email_;
}
inline bool C_SIGNUP::skip_email() const {
  // @@protoc_insertion_point(field_get:Protocol.C_SIGNUP.skip_email)
  return _internal_skip_email();
}
inline void C_SIGNUP::_internal_set_skip_email(bool value) {
  
  _impl_.skip_email_ = value;
}
inline void C_SIGNUP::set_skip_email(bool value) {
  _internal_set_skip_email(value);
  // @@protoc_insertion_point(field_set:Protocol.C_SIGNUP.skip_email)
}

// -------------------------------------------------------------------

// S_SIGNUP

// bool success = 1;
inline void S_SIGNUP::clear_success() {
  _impl_.success_ = false;
}
inline bool S_SIGNUP::_internal_success() const {
  return _impl_.success_;
}
inline bool S_SIGNUP::success() const {
  // @@protoc_insertion_point(field_get:Protocol.S_SIGNUP.success)
  return _internal_success();
}
inline void S_SIGNUP::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void S_SIGNUP::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:Protocol.S_SIGNUP.success)
}

// bool skip_email = 2;
inline void S_SIGNUP::clear_skip_email() {
  _impl_.skip_email_ = false;
}
inline bool S_SIGNUP::_internal_skip_email() const {
  return _impl_.skip_email_;
}
inline bool S_SIGNUP::skip_email() const {
  // @@protoc_insertion_point(field_get:Protocol.S_SIGNUP.skip_email)
  return _internal_skip_email();
}
inline void S_SIGNUP::_internal_set_skip_email(bool value) {
  
  _impl_.skip_email_ = value;
}
inline void S_SIGNUP::set_skip_email(bool value) {
  _internal_set_skip_email(value);
  // @@protoc_insertion_point(field_set:Protocol.S_SIGNUP.skip_email)
}

// string temp_id = 3;
inline void S_SIGNUP::clear_temp_id() {
  _impl_.temp_id_.ClearToEmpty();
}
inline const std::string& S_SIGNUP::temp_id() const {
  // @@protoc_insertion_point(field_get:Protocol.S_SIGNUP.temp_id)
  return _internal_temp_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void S_SIGNUP::set_temp_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.temp_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.S_SIGNUP.temp_id)
}
inline std::string* S_SIGNUP::mutable_temp_id() {
  std::string* _s = _internal_mutable_temp_id();
  // @@protoc_insertion_point(field_mutable:Protocol.S_SIGNUP.temp_id)
  return _s;
}
inline const std::string& S_SIGNUP::_internal_temp_id() const {
  return _impl_.temp_id_.Get();
}
inline void S_SIGNUP::_internal_set_temp_id(const std::string& value) {
  
  _impl_.temp_id_.Set(value, GetArenaForAllocation());
}
inline std::string* S_SIGNUP::_internal_mutable_temp_id() {
  
  return _impl_.temp_id_.Mutable(GetArenaForAllocation());
}
inline std::string* S_SIGNUP::release_temp_id() {
  // @@protoc_insertion_point(field_release:Protocol.S_SIGNUP.temp_id)
  return _impl_.temp_id_.Release();
}
inline void S_SIGNUP::set_allocated_temp_id(std::string* temp_id) {
  if (temp_id != nullptr) {
    
  } else {
    
  }
  _impl_.temp_id_.SetAllocated(temp_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.temp_id_.IsDefault()) {
    _impl_.temp_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.S_SIGNUP.temp_id)
}

// -------------------------------------------------------------------

// C_VERIFY_MAIL_REQ

// string temp_id = 1;
inline void C_VERIFY_MAIL_REQ::clear_temp_id() {
  _impl_.temp_id_.ClearToEmpty();
}
inline const std::string& C_VERIFY_MAIL_REQ::temp_id() const {
  // @@protoc_insertion_point(field_get:Protocol.C_VERIFY_MAIL_REQ.temp_id)
  return _internal_temp_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void C_VERIFY_MAIL_REQ::set_temp_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.temp_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.C_VERIFY_MAIL_REQ.temp_id)
}
inline std::string* C_VERIFY_MAIL_REQ::mutable_temp_id() {
  std::string* _s = _internal_mutable_temp_id();
  // @@protoc_insertion_point(field_mutable:Protocol.C_VERIFY_MAIL_REQ.temp_id)
  return _s;
}
inline const std::string& C_VERIFY_MAIL_REQ::_internal_temp_id() const {
  return _impl_.temp_id_.Get();
}
inline void C_VERIFY_MAIL_REQ::_internal_set_temp_id(const std::string& value) {
  
  _impl_.temp_id_.Set(value, GetArenaForAllocation());
}
inline std::string* C_VERIFY_MAIL_REQ::_internal_mutable_temp_id() {
  
  return _impl_.temp_id_.Mutable(GetArenaForAllocation());
}
inline std::string* C_VERIFY_MAIL_REQ::release_temp_id() {
  // @@protoc_insertion_point(field_release:Protocol.C_VERIFY_MAIL_REQ.temp_id)
  return _impl_.temp_id_.Release();
}
inline void C_VERIFY_MAIL_REQ::set_allocated_temp_id(std::string* temp_id) {
  if (temp_id != nullptr) {
    
  } else {
    
  }
  _impl_.temp_id_.SetAllocated(temp_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.temp_id_.IsDefault()) {
    _impl_.temp_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.C_VERIFY_MAIL_REQ.temp_id)
}

// -------------------------------------------------------------------

// S_VERIFY_MAIL_REQ

// bool success = 1;
inline void S_VERIFY_MAIL_REQ::clear_success() {
  _impl_.success_ = false;
}
inline bool S_VERIFY_MAIL_REQ::_internal_success() const {
  return _impl_.success_;
}
inline bool S_VERIFY_MAIL_REQ::success() const {
  // @@protoc_insertion_point(field_get:Protocol.S_VERIFY_MAIL_REQ.success)
  return _internal_success();
}
inline void S_VERIFY_MAIL_REQ::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void S_VERIFY_MAIL_REQ::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:Protocol.S_VERIFY_MAIL_REQ.success)
}

// -------------------------------------------------------------------

// C_VERIFY_EMAIL_CODE

// string temp_id = 1;
inline void C_VERIFY_EMAIL_CODE::clear_temp_id() {
  _impl_.temp_id_.ClearToEmpty();
}
inline const std::string& C_VERIFY_EMAIL_CODE::temp_id() const {
  // @@protoc_insertion_point(field_get:Protocol.C_VERIFY_EMAIL_CODE.temp_id)
  return _internal_temp_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void C_VERIFY_EMAIL_CODE::set_temp_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.temp_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.C_VERIFY_EMAIL_CODE.temp_id)
}
inline std::string* C_VERIFY_EMAIL_CODE::mutable_temp_id() {
  std::string* _s = _internal_mutable_temp_id();
  // @@protoc_insertion_point(field_mutable:Protocol.C_VERIFY_EMAIL_CODE.temp_id)
  return _s;
}
inline const std::string& C_VERIFY_EMAIL_CODE::_internal_temp_id() const {
  return _impl_.temp_id_.Get();
}
inline void C_VERIFY_EMAIL_CODE::_internal_set_temp_id(const std::string& value) {
  
  _impl_.temp_id_.Set(value, GetArenaForAllocation());
}
inline std::string* C_VERIFY_EMAIL_CODE::_internal_mutable_temp_id() {
  
  return _impl_.temp_id_.Mutable(GetArenaForAllocation());
}
inline std::string* C_VERIFY_EMAIL_CODE::release_temp_id() {
  // @@protoc_insertion_point(field_release:Protocol.C_VERIFY_EMAIL_CODE.temp_id)
  return _impl_.temp_id_.Release();
}
inline void C_VERIFY_EMAIL_CODE::set_allocated_temp_id(std::string* temp_id) {
  if (temp_id != nullptr) {
    
  } else {
    
  }
  _impl_.temp_id_.SetAllocated(temp_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.temp_id_.IsDefault()) {
    _impl_.temp_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.C_VERIFY_EMAIL_CODE.temp_id)
}

// string verify_code = 2;
inline void C_VERIFY_EMAIL_CODE::clear_verify_code() {
  _impl_.verify_code_.ClearToEmpty();
}
inline const std::string& C_VERIFY_EMAIL_CODE::verify_code() const {
  // @@protoc_insertion_point(field_get:Protocol.C_VERIFY_EMAIL_CODE.verify_code)
  return _internal_verify_code();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void C_VERIFY_EMAIL_CODE::set_verify_code(ArgT0&& arg0, ArgT... args) {
 
 _impl_.verify_code_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.C_VERIFY_EMAIL_CODE.verify_code)
}
inline std::string* C_VERIFY_EMAIL_CODE::mutable_verify_code() {
  std::string* _s = _internal_mutable_verify_code();
  // @@protoc_insertion_point(field_mutable:Protocol.C_VERIFY_EMAIL_CODE.verify_code)
  return _s;
}
inline const std::string& C_VERIFY_EMAIL_CODE::_internal_verify_code() const {
  return _impl_.verify_code_.Get();
}
inline void C_VERIFY_EMAIL_CODE::_internal_set_verify_code(const std::string& value) {
  
  _impl_.verify_code_.Set(value, GetArenaForAllocation());
}
inline std::string* C_VERIFY_EMAIL_CODE::_internal_mutable_verify_code() {
  
  return _impl_.verify_code_.Mutable(GetArenaForAllocation());
}
inline std::string* C_VERIFY_EMAIL_CODE::release_verify_code() {
  // @@protoc_insertion_point(field_release:Protocol.C_VERIFY_EMAIL_CODE.verify_code)
  return _impl_.verify_code_.Release();
}
inline void C_VERIFY_EMAIL_CODE::set_allocated_verify_code(std::string* verify_code) {
  if (verify_code != nullptr) {
    
  } else {
    
  }
  _impl_.verify_code_.SetAllocated(verify_code, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.verify_code_.IsDefault()) {
    _impl_.verify_code_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.C_VERIFY_EMAIL_CODE.verify_code)
}

// -------------------------------------------------------------------

// S_VERIFY_EMAIL_CODE

// bool success = 1;
inline void S_VERIFY_EMAIL_CODE::clear_success() {
  _impl_.success_ = false;
}
inline bool S_VERIFY_EMAIL_CODE::_internal_success() const {
  return _impl_.success_;
}
inline bool S_VERIFY_EMAIL_CODE::success() const {
  // @@protoc_insertion_point(field_get:Protocol.S_VERIFY_EMAIL_CODE.success)
  return _internal_success();
}
inline void S_VERIFY_EMAIL_CODE::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void S_VERIFY_EMAIL_CODE::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:Protocol.S_VERIFY_EMAIL_CODE.success)
}

// bool expired = 2;
inline void S_VERIFY_EMAIL_CODE::clear_expired() {
  _impl_.expired_ = false;
}
inline bool S_VERIFY_EMAIL_CODE::_internal_expired() const {
  return _impl_.expired_;
}
inline bool S_VERIFY_EMAIL_CODE::expired() const {
  // @@protoc_insertion_point(field_get:Protocol.S_VERIFY_EMAIL_CODE.expired)
  return _internal_expired();
}
inline void S_VERIFY_EMAIL_CODE::_internal_set_expired(bool value) {
  
  _impl_.expired_ = value;
}
inline void S_VERIFY_EMAIL_CODE::set_expired(bool value) {
  _internal_set_expired(value);
  // @@protoc_insertion_point(field_set:Protocol.S_VERIFY_EMAIL_CODE.expired)
}

// -------------------------------------------------------------------

// C_LOGIN

// string nickname = 1;
inline void C_LOGIN::clear_nickname() {
  _impl_.nickname_.ClearToEmpty();
}
inline const std::string& C_LOGIN::nickname() const {
  // @@protoc_insertion_point(field_get:Protocol.C_LOGIN.nickname)
  return _internal_nickname();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void C_LOGIN::set_nickname(ArgT0&& arg0, ArgT... args) {
 
 _impl_.nickname_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.C_LOGIN.nickname)
}
inline std::string* C_LOGIN::mutable_nickname() {
  std::string* _s = _internal_mutable_nickname();
  // @@protoc_insertion_point(field_mutable:Protocol.C_LOGIN.nickname)
  return _s;
}
inline const std::string& C_LOGIN::_internal_nickname() const {
  return _impl_.nickname_.Get();
}
inline void C_LOGIN::_internal_set_nickname(const std::string& value) {
  
  _impl_.nickname_.Set(value, GetArenaForAllocation());
}
inline std::string* C_LOGIN::_internal_mutable_nickname() {
  
  return _impl_.nickname_.Mutable(GetArenaForAllocation());
}
inline std::string* C_LOGIN::release_nickname() {
  // @@protoc_insertion_point(field_release:Protocol.C_LOGIN.nickname)
  return _impl_.nickname_.Release();
}
inline void C_LOGIN::set_allocated_nickname(std::string* nickname) {
  if (nickname != nullptr) {
    
  } else {
    
  }
  _impl_.nickname_.SetAllocated(nickname, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.nickname_.IsDefault()) {
    _impl_.nickname_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.C_LOGIN.nickname)
}

// string password = 2;
inline void C_LOGIN::clear_password() {
  _impl_.password_.ClearToEmpty();
}
inline const std::string& C_LOGIN::password() const {
  // @@protoc_insertion_point(field_get:Protocol.C_LOGIN.password)
  return _internal_password();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void C_LOGIN::set_password(ArgT0&& arg0, ArgT... args) {
 
 _impl_.password_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.C_LOGIN.password)
}
inline std::string* C_LOGIN::mutable_password() {
  std::string* _s = _internal_mutable_password();
  // @@protoc_insertion_point(field_mutable:Protocol.C_LOGIN.password)
  return _s;
}
inline const std::string& C_LOGIN::_internal_password() const {
  return _impl_.password_.Get();
}
inline void C_LOGIN::_internal_set_password(const std::string& value) {
  
  _impl_.password_.Set(value, GetArenaForAllocation());
}
inline std::string* C_LOGIN::_internal_mutable_password() {
  
  return _impl_.password_.Mutable(GetArenaForAllocation());
}
inline std::string* C_LOGIN::release_password() {
  // @@protoc_insertion_point(field_release:Protocol.C_LOGIN.password)
  return _impl_.password_.Release();
}
inline void C_LOGIN::set_allocated_password(std::string* password) {
  if (password != nullptr) {
    
  } else {
    
  }
  _impl_.password_.SetAllocated(password, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.password_.IsDefault()) {
    _impl_.password_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.C_LOGIN.password)
}

// -------------------------------------------------------------------

// S_LOGIN

// bool success = 1;
inline void S_LOGIN::clear_success() {
  _impl_.success_ = false;
}
inline bool S_LOGIN::_internal_success() const {
  return _impl_.success_;
}
inline bool S_LOGIN::success() const {
  // @@protoc_insertion_point(field_get:Protocol.S_LOGIN.success)
  return _internal_success();
}
inline void S_LOGIN::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void S_LOGIN::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:Protocol.S_LOGIN.success)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Protocol_2eproto
