// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocol.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Protocol_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Protocol_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Protocol_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Protocol_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Protocol_2eproto;
namespace Protocol {
class AC_LOGIN;
struct AC_LOGINDefaultTypeInternal;
extern AC_LOGINDefaultTypeInternal _AC_LOGIN_default_instance_;
class AC_SIGNUP;
struct AC_SIGNUPDefaultTypeInternal;
extern AC_SIGNUPDefaultTypeInternal _AC_SIGNUP_default_instance_;
class AC_VERIFY_EMAIL_CODE;
struct AC_VERIFY_EMAIL_CODEDefaultTypeInternal;
extern AC_VERIFY_EMAIL_CODEDefaultTypeInternal _AC_VERIFY_EMAIL_CODE_default_instance_;
class AC_VERIFY_MAIL_REQ;
struct AC_VERIFY_MAIL_REQDefaultTypeInternal;
extern AC_VERIFY_MAIL_REQDefaultTypeInternal _AC_VERIFY_MAIL_REQ_default_instance_;
class AS_LOGIN;
struct AS_LOGINDefaultTypeInternal;
extern AS_LOGINDefaultTypeInternal _AS_LOGIN_default_instance_;
class AS_SIGNUP;
struct AS_SIGNUPDefaultTypeInternal;
extern AS_SIGNUPDefaultTypeInternal _AS_SIGNUP_default_instance_;
class AS_VERIFY_EMAIL_CODE;
struct AS_VERIFY_EMAIL_CODEDefaultTypeInternal;
extern AS_VERIFY_EMAIL_CODEDefaultTypeInternal _AS_VERIFY_EMAIL_CODE_default_instance_;
class AS_VERIFY_MAIL_REQ;
struct AS_VERIFY_MAIL_REQDefaultTypeInternal;
extern AS_VERIFY_MAIL_REQDefaultTypeInternal _AS_VERIFY_MAIL_REQ_default_instance_;
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::Protocol::AC_LOGIN* Arena::CreateMaybeMessage<::Protocol::AC_LOGIN>(Arena*);
template<> ::Protocol::AC_SIGNUP* Arena::CreateMaybeMessage<::Protocol::AC_SIGNUP>(Arena*);
template<> ::Protocol::AC_VERIFY_EMAIL_CODE* Arena::CreateMaybeMessage<::Protocol::AC_VERIFY_EMAIL_CODE>(Arena*);
template<> ::Protocol::AC_VERIFY_MAIL_REQ* Arena::CreateMaybeMessage<::Protocol::AC_VERIFY_MAIL_REQ>(Arena*);
template<> ::Protocol::AS_LOGIN* Arena::CreateMaybeMessage<::Protocol::AS_LOGIN>(Arena*);
template<> ::Protocol::AS_SIGNUP* Arena::CreateMaybeMessage<::Protocol::AS_SIGNUP>(Arena*);
template<> ::Protocol::AS_VERIFY_EMAIL_CODE* Arena::CreateMaybeMessage<::Protocol::AS_VERIFY_EMAIL_CODE>(Arena*);
template<> ::Protocol::AS_VERIFY_MAIL_REQ* Arena::CreateMaybeMessage<::Protocol::AS_VERIFY_MAIL_REQ>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

// ===================================================================

class AC_SIGNUP final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.AC_SIGNUP) */ {
 public:
  inline AC_SIGNUP() : AC_SIGNUP(nullptr) {}
  ~AC_SIGNUP() override;
  explicit PROTOBUF_CONSTEXPR AC_SIGNUP(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AC_SIGNUP(const AC_SIGNUP& from);
  AC_SIGNUP(AC_SIGNUP&& from) noexcept
    : AC_SIGNUP() {
    *this = ::std::move(from);
  }

  inline AC_SIGNUP& operator=(const AC_SIGNUP& from) {
    CopyFrom(from);
    return *this;
  }
  inline AC_SIGNUP& operator=(AC_SIGNUP&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AC_SIGNUP& default_instance() {
    return *internal_default_instance();
  }
  static inline const AC_SIGNUP* internal_default_instance() {
    return reinterpret_cast<const AC_SIGNUP*>(
               &_AC_SIGNUP_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(AC_SIGNUP& a, AC_SIGNUP& b) {
    a.Swap(&b);
  }
  inline void Swap(AC_SIGNUP* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AC_SIGNUP* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AC_SIGNUP* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AC_SIGNUP>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AC_SIGNUP& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AC_SIGNUP& from) {
    AC_SIGNUP::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AC_SIGNUP* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.AC_SIGNUP";
  }
  protected:
  explicit AC_SIGNUP(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNicknameFieldNumber = 1,
    kPasswordFieldNumber = 2,
    kEmailFieldNumber = 3,
    kSkipEmailFieldNumber = 4,
  };
  // string nickname = 1;
  void clear_nickname();
  const std::string& nickname() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_nickname(ArgT0&& arg0, ArgT... args);
  std::string* mutable_nickname();
  PROTOBUF_NODISCARD std::string* release_nickname();
  void set_allocated_nickname(std::string* nickname);
  private:
  const std::string& _internal_nickname() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_nickname(const std::string& value);
  std::string* _internal_mutable_nickname();
  public:

  // string password = 2;
  void clear_password();
  const std::string& password() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_password(ArgT0&& arg0, ArgT... args);
  std::string* mutable_password();
  PROTOBUF_NODISCARD std::string* release_password();
  void set_allocated_password(std::string* password);
  private:
  const std::string& _internal_password() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_password(const std::string& value);
  std::string* _internal_mutable_password();
  public:

  // string email = 3;
  void clear_email();
  const std::string& email() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_email(ArgT0&& arg0, ArgT... args);
  std::string* mutable_email();
  PROTOBUF_NODISCARD std::string* release_email();
  void set_allocated_email(std::string* email);
  private:
  const std::string& _internal_email() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_email(const std::string& value);
  std::string* _internal_mutable_email();
  public:

  // bool skip_email = 4;
  void clear_skip_email();
  bool skip_email() const;
  void set_skip_email(bool value);
  private:
  bool _internal_skip_email() const;
  void _internal_set_skip_email(bool value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.AC_SIGNUP)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr nickname_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr password_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr email_;
    bool skip_email_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class AS_SIGNUP final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.AS_SIGNUP) */ {
 public:
  inline AS_SIGNUP() : AS_SIGNUP(nullptr) {}
  ~AS_SIGNUP() override;
  explicit PROTOBUF_CONSTEXPR AS_SIGNUP(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AS_SIGNUP(const AS_SIGNUP& from);
  AS_SIGNUP(AS_SIGNUP&& from) noexcept
    : AS_SIGNUP() {
    *this = ::std::move(from);
  }

  inline AS_SIGNUP& operator=(const AS_SIGNUP& from) {
    CopyFrom(from);
    return *this;
  }
  inline AS_SIGNUP& operator=(AS_SIGNUP&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AS_SIGNUP& default_instance() {
    return *internal_default_instance();
  }
  static inline const AS_SIGNUP* internal_default_instance() {
    return reinterpret_cast<const AS_SIGNUP*>(
               &_AS_SIGNUP_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(AS_SIGNUP& a, AS_SIGNUP& b) {
    a.Swap(&b);
  }
  inline void Swap(AS_SIGNUP* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AS_SIGNUP* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AS_SIGNUP* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AS_SIGNUP>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AS_SIGNUP& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AS_SIGNUP& from) {
    AS_SIGNUP::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AS_SIGNUP* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.AS_SIGNUP";
  }
  protected:
  explicit AS_SIGNUP(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTempIdFieldNumber = 3,
    kReasonFieldNumber = 4,
    kSuccessFieldNumber = 1,
    kSkipEmailFieldNumber = 2,
  };
  // string temp_id = 3;
  void clear_temp_id();
  const std::string& temp_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_temp_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_temp_id();
  PROTOBUF_NODISCARD std::string* release_temp_id();
  void set_allocated_temp_id(std::string* temp_id);
  private:
  const std::string& _internal_temp_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_temp_id(const std::string& value);
  std::string* _internal_mutable_temp_id();
  public:

  // string reason = 4;
  void clear_reason();
  const std::string& reason() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_reason(ArgT0&& arg0, ArgT... args);
  std::string* mutable_reason();
  PROTOBUF_NODISCARD std::string* release_reason();
  void set_allocated_reason(std::string* reason);
  private:
  const std::string& _internal_reason() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_reason(const std::string& value);
  std::string* _internal_mutable_reason();
  public:

  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // bool skip_email = 2;
  void clear_skip_email();
  bool skip_email() const;
  void set_skip_email(bool value);
  private:
  bool _internal_skip_email() const;
  void _internal_set_skip_email(bool value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.AS_SIGNUP)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr temp_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr reason_;
    bool success_;
    bool skip_email_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class AC_VERIFY_MAIL_REQ final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.AC_VERIFY_MAIL_REQ) */ {
 public:
  inline AC_VERIFY_MAIL_REQ() : AC_VERIFY_MAIL_REQ(nullptr) {}
  ~AC_VERIFY_MAIL_REQ() override;
  explicit PROTOBUF_CONSTEXPR AC_VERIFY_MAIL_REQ(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AC_VERIFY_MAIL_REQ(const AC_VERIFY_MAIL_REQ& from);
  AC_VERIFY_MAIL_REQ(AC_VERIFY_MAIL_REQ&& from) noexcept
    : AC_VERIFY_MAIL_REQ() {
    *this = ::std::move(from);
  }

  inline AC_VERIFY_MAIL_REQ& operator=(const AC_VERIFY_MAIL_REQ& from) {
    CopyFrom(from);
    return *this;
  }
  inline AC_VERIFY_MAIL_REQ& operator=(AC_VERIFY_MAIL_REQ&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AC_VERIFY_MAIL_REQ& default_instance() {
    return *internal_default_instance();
  }
  static inline const AC_VERIFY_MAIL_REQ* internal_default_instance() {
    return reinterpret_cast<const AC_VERIFY_MAIL_REQ*>(
               &_AC_VERIFY_MAIL_REQ_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(AC_VERIFY_MAIL_REQ& a, AC_VERIFY_MAIL_REQ& b) {
    a.Swap(&b);
  }
  inline void Swap(AC_VERIFY_MAIL_REQ* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AC_VERIFY_MAIL_REQ* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AC_VERIFY_MAIL_REQ* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AC_VERIFY_MAIL_REQ>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AC_VERIFY_MAIL_REQ& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AC_VERIFY_MAIL_REQ& from) {
    AC_VERIFY_MAIL_REQ::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AC_VERIFY_MAIL_REQ* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.AC_VERIFY_MAIL_REQ";
  }
  protected:
  explicit AC_VERIFY_MAIL_REQ(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTempIdFieldNumber = 1,
  };
  // string temp_id = 1;
  void clear_temp_id();
  const std::string& temp_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_temp_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_temp_id();
  PROTOBUF_NODISCARD std::string* release_temp_id();
  void set_allocated_temp_id(std::string* temp_id);
  private:
  const std::string& _internal_temp_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_temp_id(const std::string& value);
  std::string* _internal_mutable_temp_id();
  public:

  // @@protoc_insertion_point(class_scope:Protocol.AC_VERIFY_MAIL_REQ)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr temp_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class AS_VERIFY_MAIL_REQ final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.AS_VERIFY_MAIL_REQ) */ {
 public:
  inline AS_VERIFY_MAIL_REQ() : AS_VERIFY_MAIL_REQ(nullptr) {}
  ~AS_VERIFY_MAIL_REQ() override;
  explicit PROTOBUF_CONSTEXPR AS_VERIFY_MAIL_REQ(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AS_VERIFY_MAIL_REQ(const AS_VERIFY_MAIL_REQ& from);
  AS_VERIFY_MAIL_REQ(AS_VERIFY_MAIL_REQ&& from) noexcept
    : AS_VERIFY_MAIL_REQ() {
    *this = ::std::move(from);
  }

  inline AS_VERIFY_MAIL_REQ& operator=(const AS_VERIFY_MAIL_REQ& from) {
    CopyFrom(from);
    return *this;
  }
  inline AS_VERIFY_MAIL_REQ& operator=(AS_VERIFY_MAIL_REQ&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AS_VERIFY_MAIL_REQ& default_instance() {
    return *internal_default_instance();
  }
  static inline const AS_VERIFY_MAIL_REQ* internal_default_instance() {
    return reinterpret_cast<const AS_VERIFY_MAIL_REQ*>(
               &_AS_VERIFY_MAIL_REQ_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(AS_VERIFY_MAIL_REQ& a, AS_VERIFY_MAIL_REQ& b) {
    a.Swap(&b);
  }
  inline void Swap(AS_VERIFY_MAIL_REQ* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AS_VERIFY_MAIL_REQ* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AS_VERIFY_MAIL_REQ* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AS_VERIFY_MAIL_REQ>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AS_VERIFY_MAIL_REQ& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AS_VERIFY_MAIL_REQ& from) {
    AS_VERIFY_MAIL_REQ::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AS_VERIFY_MAIL_REQ* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.AS_VERIFY_MAIL_REQ";
  }
  protected:
  explicit AS_VERIFY_MAIL_REQ(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTempIdFieldNumber = 2,
    kReasonFieldNumber = 4,
    kSuccessFieldNumber = 1,
    kExpiredFieldNumber = 3,
  };
  // string temp_id = 2;
  void clear_temp_id();
  const std::string& temp_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_temp_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_temp_id();
  PROTOBUF_NODISCARD std::string* release_temp_id();
  void set_allocated_temp_id(std::string* temp_id);
  private:
  const std::string& _internal_temp_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_temp_id(const std::string& value);
  std::string* _internal_mutable_temp_id();
  public:

  // string reason = 4;
  void clear_reason();
  const std::string& reason() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_reason(ArgT0&& arg0, ArgT... args);
  std::string* mutable_reason();
  PROTOBUF_NODISCARD std::string* release_reason();
  void set_allocated_reason(std::string* reason);
  private:
  const std::string& _internal_reason() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_reason(const std::string& value);
  std::string* _internal_mutable_reason();
  public:

  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // bool expired = 3;
  void clear_expired();
  bool expired() const;
  void set_expired(bool value);
  private:
  bool _internal_expired() const;
  void _internal_set_expired(bool value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.AS_VERIFY_MAIL_REQ)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr temp_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr reason_;
    bool success_;
    bool expired_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class AC_VERIFY_EMAIL_CODE final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.AC_VERIFY_EMAIL_CODE) */ {
 public:
  inline AC_VERIFY_EMAIL_CODE() : AC_VERIFY_EMAIL_CODE(nullptr) {}
  ~AC_VERIFY_EMAIL_CODE() override;
  explicit PROTOBUF_CONSTEXPR AC_VERIFY_EMAIL_CODE(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AC_VERIFY_EMAIL_CODE(const AC_VERIFY_EMAIL_CODE& from);
  AC_VERIFY_EMAIL_CODE(AC_VERIFY_EMAIL_CODE&& from) noexcept
    : AC_VERIFY_EMAIL_CODE() {
    *this = ::std::move(from);
  }

  inline AC_VERIFY_EMAIL_CODE& operator=(const AC_VERIFY_EMAIL_CODE& from) {
    CopyFrom(from);
    return *this;
  }
  inline AC_VERIFY_EMAIL_CODE& operator=(AC_VERIFY_EMAIL_CODE&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AC_VERIFY_EMAIL_CODE& default_instance() {
    return *internal_default_instance();
  }
  static inline const AC_VERIFY_EMAIL_CODE* internal_default_instance() {
    return reinterpret_cast<const AC_VERIFY_EMAIL_CODE*>(
               &_AC_VERIFY_EMAIL_CODE_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(AC_VERIFY_EMAIL_CODE& a, AC_VERIFY_EMAIL_CODE& b) {
    a.Swap(&b);
  }
  inline void Swap(AC_VERIFY_EMAIL_CODE* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AC_VERIFY_EMAIL_CODE* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AC_VERIFY_EMAIL_CODE* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AC_VERIFY_EMAIL_CODE>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AC_VERIFY_EMAIL_CODE& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AC_VERIFY_EMAIL_CODE& from) {
    AC_VERIFY_EMAIL_CODE::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AC_VERIFY_EMAIL_CODE* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.AC_VERIFY_EMAIL_CODE";
  }
  protected:
  explicit AC_VERIFY_EMAIL_CODE(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTempIdFieldNumber = 1,
    kVerifyCodeFieldNumber = 2,
  };
  // string temp_id = 1;
  void clear_temp_id();
  const std::string& temp_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_temp_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_temp_id();
  PROTOBUF_NODISCARD std::string* release_temp_id();
  void set_allocated_temp_id(std::string* temp_id);
  private:
  const std::string& _internal_temp_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_temp_id(const std::string& value);
  std::string* _internal_mutable_temp_id();
  public:

  // string verify_code = 2;
  void clear_verify_code();
  const std::string& verify_code() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_verify_code(ArgT0&& arg0, ArgT... args);
  std::string* mutable_verify_code();
  PROTOBUF_NODISCARD std::string* release_verify_code();
  void set_allocated_verify_code(std::string* verify_code);
  private:
  const std::string& _internal_verify_code() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_verify_code(const std::string& value);
  std::string* _internal_mutable_verify_code();
  public:

  // @@protoc_insertion_point(class_scope:Protocol.AC_VERIFY_EMAIL_CODE)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr temp_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr verify_code_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class AS_VERIFY_EMAIL_CODE final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.AS_VERIFY_EMAIL_CODE) */ {
 public:
  inline AS_VERIFY_EMAIL_CODE() : AS_VERIFY_EMAIL_CODE(nullptr) {}
  ~AS_VERIFY_EMAIL_CODE() override;
  explicit PROTOBUF_CONSTEXPR AS_VERIFY_EMAIL_CODE(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AS_VERIFY_EMAIL_CODE(const AS_VERIFY_EMAIL_CODE& from);
  AS_VERIFY_EMAIL_CODE(AS_VERIFY_EMAIL_CODE&& from) noexcept
    : AS_VERIFY_EMAIL_CODE() {
    *this = ::std::move(from);
  }

  inline AS_VERIFY_EMAIL_CODE& operator=(const AS_VERIFY_EMAIL_CODE& from) {
    CopyFrom(from);
    return *this;
  }
  inline AS_VERIFY_EMAIL_CODE& operator=(AS_VERIFY_EMAIL_CODE&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AS_VERIFY_EMAIL_CODE& default_instance() {
    return *internal_default_instance();
  }
  static inline const AS_VERIFY_EMAIL_CODE* internal_default_instance() {
    return reinterpret_cast<const AS_VERIFY_EMAIL_CODE*>(
               &_AS_VERIFY_EMAIL_CODE_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(AS_VERIFY_EMAIL_CODE& a, AS_VERIFY_EMAIL_CODE& b) {
    a.Swap(&b);
  }
  inline void Swap(AS_VERIFY_EMAIL_CODE* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AS_VERIFY_EMAIL_CODE* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AS_VERIFY_EMAIL_CODE* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AS_VERIFY_EMAIL_CODE>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AS_VERIFY_EMAIL_CODE& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AS_VERIFY_EMAIL_CODE& from) {
    AS_VERIFY_EMAIL_CODE::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AS_VERIFY_EMAIL_CODE* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.AS_VERIFY_EMAIL_CODE";
  }
  protected:
  explicit AS_VERIFY_EMAIL_CODE(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNicknameFieldNumber = 3,
    kReasonFieldNumber = 4,
    kSuccessFieldNumber = 1,
    kExpiredFieldNumber = 2,
  };
  // string nickname = 3;
  void clear_nickname();
  const std::string& nickname() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_nickname(ArgT0&& arg0, ArgT... args);
  std::string* mutable_nickname();
  PROTOBUF_NODISCARD std::string* release_nickname();
  void set_allocated_nickname(std::string* nickname);
  private:
  const std::string& _internal_nickname() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_nickname(const std::string& value);
  std::string* _internal_mutable_nickname();
  public:

  // string reason = 4;
  void clear_reason();
  const std::string& reason() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_reason(ArgT0&& arg0, ArgT... args);
  std::string* mutable_reason();
  PROTOBUF_NODISCARD std::string* release_reason();
  void set_allocated_reason(std::string* reason);
  private:
  const std::string& _internal_reason() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_reason(const std::string& value);
  std::string* _internal_mutable_reason();
  public:

  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // bool expired = 2;
  void clear_expired();
  bool expired() const;
  void set_expired(bool value);
  private:
  bool _internal_expired() const;
  void _internal_set_expired(bool value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.AS_VERIFY_EMAIL_CODE)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr nickname_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr reason_;
    bool success_;
    bool expired_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class AC_LOGIN final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.AC_LOGIN) */ {
 public:
  inline AC_LOGIN() : AC_LOGIN(nullptr) {}
  ~AC_LOGIN() override;
  explicit PROTOBUF_CONSTEXPR AC_LOGIN(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AC_LOGIN(const AC_LOGIN& from);
  AC_LOGIN(AC_LOGIN&& from) noexcept
    : AC_LOGIN() {
    *this = ::std::move(from);
  }

  inline AC_LOGIN& operator=(const AC_LOGIN& from) {
    CopyFrom(from);
    return *this;
  }
  inline AC_LOGIN& operator=(AC_LOGIN&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AC_LOGIN& default_instance() {
    return *internal_default_instance();
  }
  static inline const AC_LOGIN* internal_default_instance() {
    return reinterpret_cast<const AC_LOGIN*>(
               &_AC_LOGIN_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(AC_LOGIN& a, AC_LOGIN& b) {
    a.Swap(&b);
  }
  inline void Swap(AC_LOGIN* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AC_LOGIN* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AC_LOGIN* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AC_LOGIN>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AC_LOGIN& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AC_LOGIN& from) {
    AC_LOGIN::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AC_LOGIN* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.AC_LOGIN";
  }
  protected:
  explicit AC_LOGIN(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNicknameFieldNumber = 1,
    kPasswordFieldNumber = 2,
  };
  // string nickname = 1;
  void clear_nickname();
  const std::string& nickname() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_nickname(ArgT0&& arg0, ArgT... args);
  std::string* mutable_nickname();
  PROTOBUF_NODISCARD std::string* release_nickname();
  void set_allocated_nickname(std::string* nickname);
  private:
  const std::string& _internal_nickname() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_nickname(const std::string& value);
  std::string* _internal_mutable_nickname();
  public:

  // string password = 2;
  void clear_password();
  const std::string& password() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_password(ArgT0&& arg0, ArgT... args);
  std::string* mutable_password();
  PROTOBUF_NODISCARD std::string* release_password();
  void set_allocated_password(std::string* password);
  private:
  const std::string& _internal_password() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_password(const std::string& value);
  std::string* _internal_mutable_password();
  public:

  // @@protoc_insertion_point(class_scope:Protocol.AC_LOGIN)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr nickname_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr password_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class AS_LOGIN final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.AS_LOGIN) */ {
 public:
  inline AS_LOGIN() : AS_LOGIN(nullptr) {}
  ~AS_LOGIN() override;
  explicit PROTOBUF_CONSTEXPR AS_LOGIN(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AS_LOGIN(const AS_LOGIN& from);
  AS_LOGIN(AS_LOGIN&& from) noexcept
    : AS_LOGIN() {
    *this = ::std::move(from);
  }

  inline AS_LOGIN& operator=(const AS_LOGIN& from) {
    CopyFrom(from);
    return *this;
  }
  inline AS_LOGIN& operator=(AS_LOGIN&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AS_LOGIN& default_instance() {
    return *internal_default_instance();
  }
  static inline const AS_LOGIN* internal_default_instance() {
    return reinterpret_cast<const AS_LOGIN*>(
               &_AS_LOGIN_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(AS_LOGIN& a, AS_LOGIN& b) {
    a.Swap(&b);
  }
  inline void Swap(AS_LOGIN* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AS_LOGIN* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AS_LOGIN* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AS_LOGIN>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AS_LOGIN& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AS_LOGIN& from) {
    AS_LOGIN::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AS_LOGIN* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.AS_LOGIN";
  }
  protected:
  explicit AS_LOGIN(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTokenFieldNumber = 4,
    kReasonFieldNumber = 5,
    kSuccessFieldNumber = 1,
    kIsBlockFieldNumber = 2,
    kFailCountFieldNumber = 3,
  };
  // string token = 4;
  void clear_token();
  const std::string& token() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_token(ArgT0&& arg0, ArgT... args);
  std::string* mutable_token();
  PROTOBUF_NODISCARD std::string* release_token();
  void set_allocated_token(std::string* token);
  private:
  const std::string& _internal_token() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_token(const std::string& value);
  std::string* _internal_mutable_token();
  public:

  // string reason = 5;
  void clear_reason();
  const std::string& reason() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_reason(ArgT0&& arg0, ArgT... args);
  std::string* mutable_reason();
  PROTOBUF_NODISCARD std::string* release_reason();
  void set_allocated_reason(std::string* reason);
  private:
  const std::string& _internal_reason() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_reason(const std::string& value);
  std::string* _internal_mutable_reason();
  public:

  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // bool is_block = 2;
  void clear_is_block();
  bool is_block() const;
  void set_is_block(bool value);
  private:
  bool _internal_is_block() const;
  void _internal_set_is_block(bool value);
  public:

  // int32 fail_count = 3;
  void clear_fail_count();
  int32_t fail_count() const;
  void set_fail_count(int32_t value);
  private:
  int32_t _internal_fail_count() const;
  void _internal_set_fail_count(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.AS_LOGIN)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr token_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr reason_;
    bool success_;
    bool is_block_;
    int32_t fail_count_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AC_SIGNUP

// string nickname = 1;
inline void AC_SIGNUP::clear_nickname() {
  _impl_.nickname_.ClearToEmpty();
}
inline const std::string& AC_SIGNUP::nickname() const {
  // @@protoc_insertion_point(field_get:Protocol.AC_SIGNUP.nickname)
  return _internal_nickname();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AC_SIGNUP::set_nickname(ArgT0&& arg0, ArgT... args) {
 
 _impl_.nickname_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.AC_SIGNUP.nickname)
}
inline std::string* AC_SIGNUP::mutable_nickname() {
  std::string* _s = _internal_mutable_nickname();
  // @@protoc_insertion_point(field_mutable:Protocol.AC_SIGNUP.nickname)
  return _s;
}
inline const std::string& AC_SIGNUP::_internal_nickname() const {
  return _impl_.nickname_.Get();
}
inline void AC_SIGNUP::_internal_set_nickname(const std::string& value) {
  
  _impl_.nickname_.Set(value, GetArenaForAllocation());
}
inline std::string* AC_SIGNUP::_internal_mutable_nickname() {
  
  return _impl_.nickname_.Mutable(GetArenaForAllocation());
}
inline std::string* AC_SIGNUP::release_nickname() {
  // @@protoc_insertion_point(field_release:Protocol.AC_SIGNUP.nickname)
  return _impl_.nickname_.Release();
}
inline void AC_SIGNUP::set_allocated_nickname(std::string* nickname) {
  if (nickname != nullptr) {
    
  } else {
    
  }
  _impl_.nickname_.SetAllocated(nickname, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.nickname_.IsDefault()) {
    _impl_.nickname_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.AC_SIGNUP.nickname)
}

// string password = 2;
inline void AC_SIGNUP::clear_password() {
  _impl_.password_.ClearToEmpty();
}
inline const std::string& AC_SIGNUP::password() const {
  // @@protoc_insertion_point(field_get:Protocol.AC_SIGNUP.password)
  return _internal_password();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AC_SIGNUP::set_password(ArgT0&& arg0, ArgT... args) {
 
 _impl_.password_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.AC_SIGNUP.password)
}
inline std::string* AC_SIGNUP::mutable_password() {
  std::string* _s = _internal_mutable_password();
  // @@protoc_insertion_point(field_mutable:Protocol.AC_SIGNUP.password)
  return _s;
}
inline const std::string& AC_SIGNUP::_internal_password() const {
  return _impl_.password_.Get();
}
inline void AC_SIGNUP::_internal_set_password(const std::string& value) {
  
  _impl_.password_.Set(value, GetArenaForAllocation());
}
inline std::string* AC_SIGNUP::_internal_mutable_password() {
  
  return _impl_.password_.Mutable(GetArenaForAllocation());
}
inline std::string* AC_SIGNUP::release_password() {
  // @@protoc_insertion_point(field_release:Protocol.AC_SIGNUP.password)
  return _impl_.password_.Release();
}
inline void AC_SIGNUP::set_allocated_password(std::string* password) {
  if (password != nullptr) {
    
  } else {
    
  }
  _impl_.password_.SetAllocated(password, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.password_.IsDefault()) {
    _impl_.password_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.AC_SIGNUP.password)
}

// string email = 3;
inline void AC_SIGNUP::clear_email() {
  _impl_.email_.ClearToEmpty();
}
inline const std::string& AC_SIGNUP::email() const {
  // @@protoc_insertion_point(field_get:Protocol.AC_SIGNUP.email)
  return _internal_email();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AC_SIGNUP::set_email(ArgT0&& arg0, ArgT... args) {
 
 _impl_.email_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.AC_SIGNUP.email)
}
inline std::string* AC_SIGNUP::mutable_email() {
  std::string* _s = _internal_mutable_email();
  // @@protoc_insertion_point(field_mutable:Protocol.AC_SIGNUP.email)
  return _s;
}
inline const std::string& AC_SIGNUP::_internal_email() const {
  return _impl_.email_.Get();
}
inline void AC_SIGNUP::_internal_set_email(const std::string& value) {
  
  _impl_.email_.Set(value, GetArenaForAllocation());
}
inline std::string* AC_SIGNUP::_internal_mutable_email() {
  
  return _impl_.email_.Mutable(GetArenaForAllocation());
}
inline std::string* AC_SIGNUP::release_email() {
  // @@protoc_insertion_point(field_release:Protocol.AC_SIGNUP.email)
  return _impl_.email_.Release();
}
inline void AC_SIGNUP::set_allocated_email(std::string* email) {
  if (email != nullptr) {
    
  } else {
    
  }
  _impl_.email_.SetAllocated(email, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.email_.IsDefault()) {
    _impl_.email_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.AC_SIGNUP.email)
}

// bool skip_email = 4;
inline void AC_SIGNUP::clear_skip_email() {
  _impl_.skip_email_ = false;
}
inline bool AC_SIGNUP::_internal_skip_email() const {
  return _impl_.skip_email_;
}
inline bool AC_SIGNUP::skip_email() const {
  // @@protoc_insertion_point(field_get:Protocol.AC_SIGNUP.skip_email)
  return _internal_skip_email();
}
inline void AC_SIGNUP::_internal_set_skip_email(bool value) {
  
  _impl_.skip_email_ = value;
}
inline void AC_SIGNUP::set_skip_email(bool value) {
  _internal_set_skip_email(value);
  // @@protoc_insertion_point(field_set:Protocol.AC_SIGNUP.skip_email)
}

// -------------------------------------------------------------------

// AS_SIGNUP

// bool success = 1;
inline void AS_SIGNUP::clear_success() {
  _impl_.success_ = false;
}
inline bool AS_SIGNUP::_internal_success() const {
  return _impl_.success_;
}
inline bool AS_SIGNUP::success() const {
  // @@protoc_insertion_point(field_get:Protocol.AS_SIGNUP.success)
  return _internal_success();
}
inline void AS_SIGNUP::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void AS_SIGNUP::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:Protocol.AS_SIGNUP.success)
}

// bool skip_email = 2;
inline void AS_SIGNUP::clear_skip_email() {
  _impl_.skip_email_ = false;
}
inline bool AS_SIGNUP::_internal_skip_email() const {
  return _impl_.skip_email_;
}
inline bool AS_SIGNUP::skip_email() const {
  // @@protoc_insertion_point(field_get:Protocol.AS_SIGNUP.skip_email)
  return _internal_skip_email();
}
inline void AS_SIGNUP::_internal_set_skip_email(bool value) {
  
  _impl_.skip_email_ = value;
}
inline void AS_SIGNUP::set_skip_email(bool value) {
  _internal_set_skip_email(value);
  // @@protoc_insertion_point(field_set:Protocol.AS_SIGNUP.skip_email)
}

// string temp_id = 3;
inline void AS_SIGNUP::clear_temp_id() {
  _impl_.temp_id_.ClearToEmpty();
}
inline const std::string& AS_SIGNUP::temp_id() const {
  // @@protoc_insertion_point(field_get:Protocol.AS_SIGNUP.temp_id)
  return _internal_temp_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AS_SIGNUP::set_temp_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.temp_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.AS_SIGNUP.temp_id)
}
inline std::string* AS_SIGNUP::mutable_temp_id() {
  std::string* _s = _internal_mutable_temp_id();
  // @@protoc_insertion_point(field_mutable:Protocol.AS_SIGNUP.temp_id)
  return _s;
}
inline const std::string& AS_SIGNUP::_internal_temp_id() const {
  return _impl_.temp_id_.Get();
}
inline void AS_SIGNUP::_internal_set_temp_id(const std::string& value) {
  
  _impl_.temp_id_.Set(value, GetArenaForAllocation());
}
inline std::string* AS_SIGNUP::_internal_mutable_temp_id() {
  
  return _impl_.temp_id_.Mutable(GetArenaForAllocation());
}
inline std::string* AS_SIGNUP::release_temp_id() {
  // @@protoc_insertion_point(field_release:Protocol.AS_SIGNUP.temp_id)
  return _impl_.temp_id_.Release();
}
inline void AS_SIGNUP::set_allocated_temp_id(std::string* temp_id) {
  if (temp_id != nullptr) {
    
  } else {
    
  }
  _impl_.temp_id_.SetAllocated(temp_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.temp_id_.IsDefault()) {
    _impl_.temp_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.AS_SIGNUP.temp_id)
}

// string reason = 4;
inline void AS_SIGNUP::clear_reason() {
  _impl_.reason_.ClearToEmpty();
}
inline const std::string& AS_SIGNUP::reason() const {
  // @@protoc_insertion_point(field_get:Protocol.AS_SIGNUP.reason)
  return _internal_reason();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AS_SIGNUP::set_reason(ArgT0&& arg0, ArgT... args) {
 
 _impl_.reason_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.AS_SIGNUP.reason)
}
inline std::string* AS_SIGNUP::mutable_reason() {
  std::string* _s = _internal_mutable_reason();
  // @@protoc_insertion_point(field_mutable:Protocol.AS_SIGNUP.reason)
  return _s;
}
inline const std::string& AS_SIGNUP::_internal_reason() const {
  return _impl_.reason_.Get();
}
inline void AS_SIGNUP::_internal_set_reason(const std::string& value) {
  
  _impl_.reason_.Set(value, GetArenaForAllocation());
}
inline std::string* AS_SIGNUP::_internal_mutable_reason() {
  
  return _impl_.reason_.Mutable(GetArenaForAllocation());
}
inline std::string* AS_SIGNUP::release_reason() {
  // @@protoc_insertion_point(field_release:Protocol.AS_SIGNUP.reason)
  return _impl_.reason_.Release();
}
inline void AS_SIGNUP::set_allocated_reason(std::string* reason) {
  if (reason != nullptr) {
    
  } else {
    
  }
  _impl_.reason_.SetAllocated(reason, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.reason_.IsDefault()) {
    _impl_.reason_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.AS_SIGNUP.reason)
}

// -------------------------------------------------------------------

// AC_VERIFY_MAIL_REQ

// string temp_id = 1;
inline void AC_VERIFY_MAIL_REQ::clear_temp_id() {
  _impl_.temp_id_.ClearToEmpty();
}
inline const std::string& AC_VERIFY_MAIL_REQ::temp_id() const {
  // @@protoc_insertion_point(field_get:Protocol.AC_VERIFY_MAIL_REQ.temp_id)
  return _internal_temp_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AC_VERIFY_MAIL_REQ::set_temp_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.temp_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.AC_VERIFY_MAIL_REQ.temp_id)
}
inline std::string* AC_VERIFY_MAIL_REQ::mutable_temp_id() {
  std::string* _s = _internal_mutable_temp_id();
  // @@protoc_insertion_point(field_mutable:Protocol.AC_VERIFY_MAIL_REQ.temp_id)
  return _s;
}
inline const std::string& AC_VERIFY_MAIL_REQ::_internal_temp_id() const {
  return _impl_.temp_id_.Get();
}
inline void AC_VERIFY_MAIL_REQ::_internal_set_temp_id(const std::string& value) {
  
  _impl_.temp_id_.Set(value, GetArenaForAllocation());
}
inline std::string* AC_VERIFY_MAIL_REQ::_internal_mutable_temp_id() {
  
  return _impl_.temp_id_.Mutable(GetArenaForAllocation());
}
inline std::string* AC_VERIFY_MAIL_REQ::release_temp_id() {
  // @@protoc_insertion_point(field_release:Protocol.AC_VERIFY_MAIL_REQ.temp_id)
  return _impl_.temp_id_.Release();
}
inline void AC_VERIFY_MAIL_REQ::set_allocated_temp_id(std::string* temp_id) {
  if (temp_id != nullptr) {
    
  } else {
    
  }
  _impl_.temp_id_.SetAllocated(temp_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.temp_id_.IsDefault()) {
    _impl_.temp_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.AC_VERIFY_MAIL_REQ.temp_id)
}

// -------------------------------------------------------------------

// AS_VERIFY_MAIL_REQ

// bool success = 1;
inline void AS_VERIFY_MAIL_REQ::clear_success() {
  _impl_.success_ = false;
}
inline bool AS_VERIFY_MAIL_REQ::_internal_success() const {
  return _impl_.success_;
}
inline bool AS_VERIFY_MAIL_REQ::success() const {
  // @@protoc_insertion_point(field_get:Protocol.AS_VERIFY_MAIL_REQ.success)
  return _internal_success();
}
inline void AS_VERIFY_MAIL_REQ::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void AS_VERIFY_MAIL_REQ::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:Protocol.AS_VERIFY_MAIL_REQ.success)
}

// string temp_id = 2;
inline void AS_VERIFY_MAIL_REQ::clear_temp_id() {
  _impl_.temp_id_.ClearToEmpty();
}
inline const std::string& AS_VERIFY_MAIL_REQ::temp_id() const {
  // @@protoc_insertion_point(field_get:Protocol.AS_VERIFY_MAIL_REQ.temp_id)
  return _internal_temp_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AS_VERIFY_MAIL_REQ::set_temp_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.temp_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.AS_VERIFY_MAIL_REQ.temp_id)
}
inline std::string* AS_VERIFY_MAIL_REQ::mutable_temp_id() {
  std::string* _s = _internal_mutable_temp_id();
  // @@protoc_insertion_point(field_mutable:Protocol.AS_VERIFY_MAIL_REQ.temp_id)
  return _s;
}
inline const std::string& AS_VERIFY_MAIL_REQ::_internal_temp_id() const {
  return _impl_.temp_id_.Get();
}
inline void AS_VERIFY_MAIL_REQ::_internal_set_temp_id(const std::string& value) {
  
  _impl_.temp_id_.Set(value, GetArenaForAllocation());
}
inline std::string* AS_VERIFY_MAIL_REQ::_internal_mutable_temp_id() {
  
  return _impl_.temp_id_.Mutable(GetArenaForAllocation());
}
inline std::string* AS_VERIFY_MAIL_REQ::release_temp_id() {
  // @@protoc_insertion_point(field_release:Protocol.AS_VERIFY_MAIL_REQ.temp_id)
  return _impl_.temp_id_.Release();
}
inline void AS_VERIFY_MAIL_REQ::set_allocated_temp_id(std::string* temp_id) {
  if (temp_id != nullptr) {
    
  } else {
    
  }
  _impl_.temp_id_.SetAllocated(temp_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.temp_id_.IsDefault()) {
    _impl_.temp_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.AS_VERIFY_MAIL_REQ.temp_id)
}

// bool expired = 3;
inline void AS_VERIFY_MAIL_REQ::clear_expired() {
  _impl_.expired_ = false;
}
inline bool AS_VERIFY_MAIL_REQ::_internal_expired() const {
  return _impl_.expired_;
}
inline bool AS_VERIFY_MAIL_REQ::expired() const {
  // @@protoc_insertion_point(field_get:Protocol.AS_VERIFY_MAIL_REQ.expired)
  return _internal_expired();
}
inline void AS_VERIFY_MAIL_REQ::_internal_set_expired(bool value) {
  
  _impl_.expired_ = value;
}
inline void AS_VERIFY_MAIL_REQ::set_expired(bool value) {
  _internal_set_expired(value);
  // @@protoc_insertion_point(field_set:Protocol.AS_VERIFY_MAIL_REQ.expired)
}

// string reason = 4;
inline void AS_VERIFY_MAIL_REQ::clear_reason() {
  _impl_.reason_.ClearToEmpty();
}
inline const std::string& AS_VERIFY_MAIL_REQ::reason() const {
  // @@protoc_insertion_point(field_get:Protocol.AS_VERIFY_MAIL_REQ.reason)
  return _internal_reason();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AS_VERIFY_MAIL_REQ::set_reason(ArgT0&& arg0, ArgT... args) {
 
 _impl_.reason_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.AS_VERIFY_MAIL_REQ.reason)
}
inline std::string* AS_VERIFY_MAIL_REQ::mutable_reason() {
  std::string* _s = _internal_mutable_reason();
  // @@protoc_insertion_point(field_mutable:Protocol.AS_VERIFY_MAIL_REQ.reason)
  return _s;
}
inline const std::string& AS_VERIFY_MAIL_REQ::_internal_reason() const {
  return _impl_.reason_.Get();
}
inline void AS_VERIFY_MAIL_REQ::_internal_set_reason(const std::string& value) {
  
  _impl_.reason_.Set(value, GetArenaForAllocation());
}
inline std::string* AS_VERIFY_MAIL_REQ::_internal_mutable_reason() {
  
  return _impl_.reason_.Mutable(GetArenaForAllocation());
}
inline std::string* AS_VERIFY_MAIL_REQ::release_reason() {
  // @@protoc_insertion_point(field_release:Protocol.AS_VERIFY_MAIL_REQ.reason)
  return _impl_.reason_.Release();
}
inline void AS_VERIFY_MAIL_REQ::set_allocated_reason(std::string* reason) {
  if (reason != nullptr) {
    
  } else {
    
  }
  _impl_.reason_.SetAllocated(reason, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.reason_.IsDefault()) {
    _impl_.reason_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.AS_VERIFY_MAIL_REQ.reason)
}

// -------------------------------------------------------------------

// AC_VERIFY_EMAIL_CODE

// string temp_id = 1;
inline void AC_VERIFY_EMAIL_CODE::clear_temp_id() {
  _impl_.temp_id_.ClearToEmpty();
}
inline const std::string& AC_VERIFY_EMAIL_CODE::temp_id() const {
  // @@protoc_insertion_point(field_get:Protocol.AC_VERIFY_EMAIL_CODE.temp_id)
  return _internal_temp_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AC_VERIFY_EMAIL_CODE::set_temp_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.temp_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.AC_VERIFY_EMAIL_CODE.temp_id)
}
inline std::string* AC_VERIFY_EMAIL_CODE::mutable_temp_id() {
  std::string* _s = _internal_mutable_temp_id();
  // @@protoc_insertion_point(field_mutable:Protocol.AC_VERIFY_EMAIL_CODE.temp_id)
  return _s;
}
inline const std::string& AC_VERIFY_EMAIL_CODE::_internal_temp_id() const {
  return _impl_.temp_id_.Get();
}
inline void AC_VERIFY_EMAIL_CODE::_internal_set_temp_id(const std::string& value) {
  
  _impl_.temp_id_.Set(value, GetArenaForAllocation());
}
inline std::string* AC_VERIFY_EMAIL_CODE::_internal_mutable_temp_id() {
  
  return _impl_.temp_id_.Mutable(GetArenaForAllocation());
}
inline std::string* AC_VERIFY_EMAIL_CODE::release_temp_id() {
  // @@protoc_insertion_point(field_release:Protocol.AC_VERIFY_EMAIL_CODE.temp_id)
  return _impl_.temp_id_.Release();
}
inline void AC_VERIFY_EMAIL_CODE::set_allocated_temp_id(std::string* temp_id) {
  if (temp_id != nullptr) {
    
  } else {
    
  }
  _impl_.temp_id_.SetAllocated(temp_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.temp_id_.IsDefault()) {
    _impl_.temp_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.AC_VERIFY_EMAIL_CODE.temp_id)
}

// string verify_code = 2;
inline void AC_VERIFY_EMAIL_CODE::clear_verify_code() {
  _impl_.verify_code_.ClearToEmpty();
}
inline const std::string& AC_VERIFY_EMAIL_CODE::verify_code() const {
  // @@protoc_insertion_point(field_get:Protocol.AC_VERIFY_EMAIL_CODE.verify_code)
  return _internal_verify_code();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AC_VERIFY_EMAIL_CODE::set_verify_code(ArgT0&& arg0, ArgT... args) {
 
 _impl_.verify_code_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.AC_VERIFY_EMAIL_CODE.verify_code)
}
inline std::string* AC_VERIFY_EMAIL_CODE::mutable_verify_code() {
  std::string* _s = _internal_mutable_verify_code();
  // @@protoc_insertion_point(field_mutable:Protocol.AC_VERIFY_EMAIL_CODE.verify_code)
  return _s;
}
inline const std::string& AC_VERIFY_EMAIL_CODE::_internal_verify_code() const {
  return _impl_.verify_code_.Get();
}
inline void AC_VERIFY_EMAIL_CODE::_internal_set_verify_code(const std::string& value) {
  
  _impl_.verify_code_.Set(value, GetArenaForAllocation());
}
inline std::string* AC_VERIFY_EMAIL_CODE::_internal_mutable_verify_code() {
  
  return _impl_.verify_code_.Mutable(GetArenaForAllocation());
}
inline std::string* AC_VERIFY_EMAIL_CODE::release_verify_code() {
  // @@protoc_insertion_point(field_release:Protocol.AC_VERIFY_EMAIL_CODE.verify_code)
  return _impl_.verify_code_.Release();
}
inline void AC_VERIFY_EMAIL_CODE::set_allocated_verify_code(std::string* verify_code) {
  if (verify_code != nullptr) {
    
  } else {
    
  }
  _impl_.verify_code_.SetAllocated(verify_code, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.verify_code_.IsDefault()) {
    _impl_.verify_code_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.AC_VERIFY_EMAIL_CODE.verify_code)
}

// -------------------------------------------------------------------

// AS_VERIFY_EMAIL_CODE

// bool success = 1;
inline void AS_VERIFY_EMAIL_CODE::clear_success() {
  _impl_.success_ = false;
}
inline bool AS_VERIFY_EMAIL_CODE::_internal_success() const {
  return _impl_.success_;
}
inline bool AS_VERIFY_EMAIL_CODE::success() const {
  // @@protoc_insertion_point(field_get:Protocol.AS_VERIFY_EMAIL_CODE.success)
  return _internal_success();
}
inline void AS_VERIFY_EMAIL_CODE::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void AS_VERIFY_EMAIL_CODE::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:Protocol.AS_VERIFY_EMAIL_CODE.success)
}

// bool expired = 2;
inline void AS_VERIFY_EMAIL_CODE::clear_expired() {
  _impl_.expired_ = false;
}
inline bool AS_VERIFY_EMAIL_CODE::_internal_expired() const {
  return _impl_.expired_;
}
inline bool AS_VERIFY_EMAIL_CODE::expired() const {
  // @@protoc_insertion_point(field_get:Protocol.AS_VERIFY_EMAIL_CODE.expired)
  return _internal_expired();
}
inline void AS_VERIFY_EMAIL_CODE::_internal_set_expired(bool value) {
  
  _impl_.expired_ = value;
}
inline void AS_VERIFY_EMAIL_CODE::set_expired(bool value) {
  _internal_set_expired(value);
  // @@protoc_insertion_point(field_set:Protocol.AS_VERIFY_EMAIL_CODE.expired)
}

// string nickname = 3;
inline void AS_VERIFY_EMAIL_CODE::clear_nickname() {
  _impl_.nickname_.ClearToEmpty();
}
inline const std::string& AS_VERIFY_EMAIL_CODE::nickname() const {
  // @@protoc_insertion_point(field_get:Protocol.AS_VERIFY_EMAIL_CODE.nickname)
  return _internal_nickname();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AS_VERIFY_EMAIL_CODE::set_nickname(ArgT0&& arg0, ArgT... args) {
 
 _impl_.nickname_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.AS_VERIFY_EMAIL_CODE.nickname)
}
inline std::string* AS_VERIFY_EMAIL_CODE::mutable_nickname() {
  std::string* _s = _internal_mutable_nickname();
  // @@protoc_insertion_point(field_mutable:Protocol.AS_VERIFY_EMAIL_CODE.nickname)
  return _s;
}
inline const std::string& AS_VERIFY_EMAIL_CODE::_internal_nickname() const {
  return _impl_.nickname_.Get();
}
inline void AS_VERIFY_EMAIL_CODE::_internal_set_nickname(const std::string& value) {
  
  _impl_.nickname_.Set(value, GetArenaForAllocation());
}
inline std::string* AS_VERIFY_EMAIL_CODE::_internal_mutable_nickname() {
  
  return _impl_.nickname_.Mutable(GetArenaForAllocation());
}
inline std::string* AS_VERIFY_EMAIL_CODE::release_nickname() {
  // @@protoc_insertion_point(field_release:Protocol.AS_VERIFY_EMAIL_CODE.nickname)
  return _impl_.nickname_.Release();
}
inline void AS_VERIFY_EMAIL_CODE::set_allocated_nickname(std::string* nickname) {
  if (nickname != nullptr) {
    
  } else {
    
  }
  _impl_.nickname_.SetAllocated(nickname, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.nickname_.IsDefault()) {
    _impl_.nickname_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.AS_VERIFY_EMAIL_CODE.nickname)
}

// string reason = 4;
inline void AS_VERIFY_EMAIL_CODE::clear_reason() {
  _impl_.reason_.ClearToEmpty();
}
inline const std::string& AS_VERIFY_EMAIL_CODE::reason() const {
  // @@protoc_insertion_point(field_get:Protocol.AS_VERIFY_EMAIL_CODE.reason)
  return _internal_reason();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AS_VERIFY_EMAIL_CODE::set_reason(ArgT0&& arg0, ArgT... args) {
 
 _impl_.reason_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.AS_VERIFY_EMAIL_CODE.reason)
}
inline std::string* AS_VERIFY_EMAIL_CODE::mutable_reason() {
  std::string* _s = _internal_mutable_reason();
  // @@protoc_insertion_point(field_mutable:Protocol.AS_VERIFY_EMAIL_CODE.reason)
  return _s;
}
inline const std::string& AS_VERIFY_EMAIL_CODE::_internal_reason() const {
  return _impl_.reason_.Get();
}
inline void AS_VERIFY_EMAIL_CODE::_internal_set_reason(const std::string& value) {
  
  _impl_.reason_.Set(value, GetArenaForAllocation());
}
inline std::string* AS_VERIFY_EMAIL_CODE::_internal_mutable_reason() {
  
  return _impl_.reason_.Mutable(GetArenaForAllocation());
}
inline std::string* AS_VERIFY_EMAIL_CODE::release_reason() {
  // @@protoc_insertion_point(field_release:Protocol.AS_VERIFY_EMAIL_CODE.reason)
  return _impl_.reason_.Release();
}
inline void AS_VERIFY_EMAIL_CODE::set_allocated_reason(std::string* reason) {
  if (reason != nullptr) {
    
  } else {
    
  }
  _impl_.reason_.SetAllocated(reason, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.reason_.IsDefault()) {
    _impl_.reason_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.AS_VERIFY_EMAIL_CODE.reason)
}

// -------------------------------------------------------------------

// AC_LOGIN

// string nickname = 1;
inline void AC_LOGIN::clear_nickname() {
  _impl_.nickname_.ClearToEmpty();
}
inline const std::string& AC_LOGIN::nickname() const {
  // @@protoc_insertion_point(field_get:Protocol.AC_LOGIN.nickname)
  return _internal_nickname();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AC_LOGIN::set_nickname(ArgT0&& arg0, ArgT... args) {
 
 _impl_.nickname_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.AC_LOGIN.nickname)
}
inline std::string* AC_LOGIN::mutable_nickname() {
  std::string* _s = _internal_mutable_nickname();
  // @@protoc_insertion_point(field_mutable:Protocol.AC_LOGIN.nickname)
  return _s;
}
inline const std::string& AC_LOGIN::_internal_nickname() const {
  return _impl_.nickname_.Get();
}
inline void AC_LOGIN::_internal_set_nickname(const std::string& value) {
  
  _impl_.nickname_.Set(value, GetArenaForAllocation());
}
inline std::string* AC_LOGIN::_internal_mutable_nickname() {
  
  return _impl_.nickname_.Mutable(GetArenaForAllocation());
}
inline std::string* AC_LOGIN::release_nickname() {
  // @@protoc_insertion_point(field_release:Protocol.AC_LOGIN.nickname)
  return _impl_.nickname_.Release();
}
inline void AC_LOGIN::set_allocated_nickname(std::string* nickname) {
  if (nickname != nullptr) {
    
  } else {
    
  }
  _impl_.nickname_.SetAllocated(nickname, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.nickname_.IsDefault()) {
    _impl_.nickname_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.AC_LOGIN.nickname)
}

// string password = 2;
inline void AC_LOGIN::clear_password() {
  _impl_.password_.ClearToEmpty();
}
inline const std::string& AC_LOGIN::password() const {
  // @@protoc_insertion_point(field_get:Protocol.AC_LOGIN.password)
  return _internal_password();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AC_LOGIN::set_password(ArgT0&& arg0, ArgT... args) {
 
 _impl_.password_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.AC_LOGIN.password)
}
inline std::string* AC_LOGIN::mutable_password() {
  std::string* _s = _internal_mutable_password();
  // @@protoc_insertion_point(field_mutable:Protocol.AC_LOGIN.password)
  return _s;
}
inline const std::string& AC_LOGIN::_internal_password() const {
  return _impl_.password_.Get();
}
inline void AC_LOGIN::_internal_set_password(const std::string& value) {
  
  _impl_.password_.Set(value, GetArenaForAllocation());
}
inline std::string* AC_LOGIN::_internal_mutable_password() {
  
  return _impl_.password_.Mutable(GetArenaForAllocation());
}
inline std::string* AC_LOGIN::release_password() {
  // @@protoc_insertion_point(field_release:Protocol.AC_LOGIN.password)
  return _impl_.password_.Release();
}
inline void AC_LOGIN::set_allocated_password(std::string* password) {
  if (password != nullptr) {
    
  } else {
    
  }
  _impl_.password_.SetAllocated(password, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.password_.IsDefault()) {
    _impl_.password_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.AC_LOGIN.password)
}

// -------------------------------------------------------------------

// AS_LOGIN

// bool success = 1;
inline void AS_LOGIN::clear_success() {
  _impl_.success_ = false;
}
inline bool AS_LOGIN::_internal_success() const {
  return _impl_.success_;
}
inline bool AS_LOGIN::success() const {
  // @@protoc_insertion_point(field_get:Protocol.AS_LOGIN.success)
  return _internal_success();
}
inline void AS_LOGIN::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void AS_LOGIN::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:Protocol.AS_LOGIN.success)
}

// bool is_block = 2;
inline void AS_LOGIN::clear_is_block() {
  _impl_.is_block_ = false;
}
inline bool AS_LOGIN::_internal_is_block() const {
  return _impl_.is_block_;
}
inline bool AS_LOGIN::is_block() const {
  // @@protoc_insertion_point(field_get:Protocol.AS_LOGIN.is_block)
  return _internal_is_block();
}
inline void AS_LOGIN::_internal_set_is_block(bool value) {
  
  _impl_.is_block_ = value;
}
inline void AS_LOGIN::set_is_block(bool value) {
  _internal_set_is_block(value);
  // @@protoc_insertion_point(field_set:Protocol.AS_LOGIN.is_block)
}

// int32 fail_count = 3;
inline void AS_LOGIN::clear_fail_count() {
  _impl_.fail_count_ = 0;
}
inline int32_t AS_LOGIN::_internal_fail_count() const {
  return _impl_.fail_count_;
}
inline int32_t AS_LOGIN::fail_count() const {
  // @@protoc_insertion_point(field_get:Protocol.AS_LOGIN.fail_count)
  return _internal_fail_count();
}
inline void AS_LOGIN::_internal_set_fail_count(int32_t value) {
  
  _impl_.fail_count_ = value;
}
inline void AS_LOGIN::set_fail_count(int32_t value) {
  _internal_set_fail_count(value);
  // @@protoc_insertion_point(field_set:Protocol.AS_LOGIN.fail_count)
}

// string token = 4;
inline void AS_LOGIN::clear_token() {
  _impl_.token_.ClearToEmpty();
}
inline const std::string& AS_LOGIN::token() const {
  // @@protoc_insertion_point(field_get:Protocol.AS_LOGIN.token)
  return _internal_token();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AS_LOGIN::set_token(ArgT0&& arg0, ArgT... args) {
 
 _impl_.token_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.AS_LOGIN.token)
}
inline std::string* AS_LOGIN::mutable_token() {
  std::string* _s = _internal_mutable_token();
  // @@protoc_insertion_point(field_mutable:Protocol.AS_LOGIN.token)
  return _s;
}
inline const std::string& AS_LOGIN::_internal_token() const {
  return _impl_.token_.Get();
}
inline void AS_LOGIN::_internal_set_token(const std::string& value) {
  
  _impl_.token_.Set(value, GetArenaForAllocation());
}
inline std::string* AS_LOGIN::_internal_mutable_token() {
  
  return _impl_.token_.Mutable(GetArenaForAllocation());
}
inline std::string* AS_LOGIN::release_token() {
  // @@protoc_insertion_point(field_release:Protocol.AS_LOGIN.token)
  return _impl_.token_.Release();
}
inline void AS_LOGIN::set_allocated_token(std::string* token) {
  if (token != nullptr) {
    
  } else {
    
  }
  _impl_.token_.SetAllocated(token, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.token_.IsDefault()) {
    _impl_.token_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.AS_LOGIN.token)
}

// string reason = 5;
inline void AS_LOGIN::clear_reason() {
  _impl_.reason_.ClearToEmpty();
}
inline const std::string& AS_LOGIN::reason() const {
  // @@protoc_insertion_point(field_get:Protocol.AS_LOGIN.reason)
  return _internal_reason();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AS_LOGIN::set_reason(ArgT0&& arg0, ArgT... args) {
 
 _impl_.reason_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.AS_LOGIN.reason)
}
inline std::string* AS_LOGIN::mutable_reason() {
  std::string* _s = _internal_mutable_reason();
  // @@protoc_insertion_point(field_mutable:Protocol.AS_LOGIN.reason)
  return _s;
}
inline const std::string& AS_LOGIN::_internal_reason() const {
  return _impl_.reason_.Get();
}
inline void AS_LOGIN::_internal_set_reason(const std::string& value) {
  
  _impl_.reason_.Set(value, GetArenaForAllocation());
}
inline std::string* AS_LOGIN::_internal_mutable_reason() {
  
  return _impl_.reason_.Mutable(GetArenaForAllocation());
}
inline std::string* AS_LOGIN::release_reason() {
  // @@protoc_insertion_point(field_release:Protocol.AS_LOGIN.reason)
  return _impl_.reason_.Release();
}
inline void AS_LOGIN::set_allocated_reason(std::string* reason) {
  if (reason != nullptr) {
    
  } else {
    
  }
  _impl_.reason_.SetAllocated(reason, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.reason_.IsDefault()) {
    _impl_.reason_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.AS_LOGIN.reason)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Protocol_2eproto
